/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_myb_helloworld */

#ifndef _Included_com_myb_helloworld
#define _Included_com_myb_helloworld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_myb_helloworld
 * Method:    test
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_myb_helloworld_test
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_myb_helloworld
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_myb_helloworld_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
